bind 0.0.0.0
protected-mode yes
port 6379

rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""
rename-command SAVE ""
rename-command BGSAVE ""
rename-command DEBUG ""
rename-command SHUTDOWN ""
rename-command MODULE ""
rename-command SCRIPT ""
